###
POST http://localhost:9000/api/users HTTP/1.1
Content-Type: application/json

{
  "identificador": "L7HU5hReQP",
  "typeUser": "client",
  "userName": "Yonatan",
  "password": "pass123",
  "email": "yon@gmail.com",
  "mascota": ["perro", "gato", "roedor"]
}

###
GET http://localhost:9000/api/users HTTP/1.1

###
GET http://localhost:9000/api/users/login HTTP/1.1
Content-Type: application/json

{
  "email":"zam@gmail.com",
  "password": "pass123"
}

###
GET http://localhost:9000/api/users/personal HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZGVudGlmaWNhZG9yIjoiM1k1VFZISHJCWCIsInR5cGVVc2VyIjoiYWRtaW4iLCJpYXQiOjE2NTE0MzQ4MzQsImV4cCI6MTY1MjY0NDQzNH0.Eb7VBvlnaEByJNDFW28wNYqw7Urnl5_PIn84__HURSg

{
  "email":"zam@gmail.com",
  "password": "pass123"
}

###
GET http://localhost:9000/api/users/L7HU5hReQP HTTP/1.1

###
POST http://localhost:9000/api/products HTTP/1.1
Content-Type: application/json

{
    "identificador": "v8d2Q",
        "categoria": "comida",
        "especie": "perro",
        "imagen": "../../img/COMIDA PERRO/imagen10.jpg",
        "nombre": "Strat - Anima",
        "precio": "$140.59",
        "oferta": "$136.37",
        "descuento": "- $4.22",
        "opciones": "600 ml"
}

###
GET http://localhost:9000/api/products HTTP/1.1

###
GET http://localhost:9000/api/products/perro/comida HTTP/1.1

###
GET http://localhost:9000/api/products/perro/ropa HTTP/1.1

###
GET http://localhost:9000/api/products/roedor/juguetes HTTP/1.1

###
GET http://localhost:9000/api/products/rwy2C HTTP/1.1

###
POST http://localhost:9000/api/address HTTP/1.1
Content-Type: application/json

{
  "identificador": "6XJe5",
  "id_cliente": "3Y5TVHHrBX",
  "codigoPostal": "55935",
  "calle": "La Cumbre",
  "numeroExterior": "S/N",
  "colonia": "San Marcos",
  "ciudad": "Otumba",
  "telefono": "6769229277"
}

###
GET http://localhost:9000/api/address/L7HU5hReQP HTTP/1.1

###
DELETE http://localhost:9000/api/address/9pU3J HTTP/1.1

###
POST http://localhost:9000/api/car HTTP/1.1
Content-Type: application/json

{
  "identificador": "P9Kgw",
  "id_cliente": "L7HU5hReQP",
  "id_producto": "L3S3S",
  "cantidad": "2",
  "precio": "136.37"
}

###
GET http://localhost:9000/api/car/71d43ce579 HTTP/1.1

###
DELETE http://localhost:9000/api/car/F6lYx HTTP/1.1